name: geocoding_web
version: 0.0.2

flutter:
  plugin:
    platforms:
      web:
        pluginClass: GeocodingWebPlugin
        fileName: geocoding_web.dart

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  geocoding: ^4.0.0
  http: ^1.5.0

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=2.0.0 <3.0.0"
