name: geocoding_web
version: 0.0.1

flutter:
  plugin:
    platforms:
      web:
        pluginClass: GeocodingWebPlugin
        fileName: geocoding_web.dart

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  geocoding: ^2.0.0
  http: ^0.13.0

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.5.0 <2.0.0"